'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TLOZ_A_Link_Between_Worlds_Save_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_betwse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_betwse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_menuitems_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menuitems_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg_menuitems_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menuitems_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_apple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_apple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_bee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_bee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_bluepotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_bluepotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_fairy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_fairy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_goldenbee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_goldenbee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_greenapple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_greenapple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_letter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_letter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_milk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_milk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_premiummilk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_premiummilk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_purplepotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_purplepotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_redpotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_redpotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_yellowpotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_yellowpotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_red_tl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_red_tl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_tl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_tl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_AdvH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_AdvH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bombs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bombs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bombs_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bombs_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bombs_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bombs_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bombs_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bombs_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_boomerang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_boomerang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_boomerang_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_boomerang_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_boomerang_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_boomerang_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_boomerang_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_boomerang_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bottles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bottles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bottles_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bottles_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bow_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bow_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bow_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bow_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bow_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bow_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bowoflight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bowoflight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_bowoflight_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_bowoflight_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_description() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_description", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_description_inventory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_description_inventory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_firerod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_firerod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_firerod_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_firerod_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_firerod_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_firerod_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_firerod_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_firerod_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_foulfruit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_foulfruit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_foulfruit_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_foulfruit_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hammer_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hammer_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hammer_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hammer_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hammer_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hammer_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_heart_0x4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_heart_0x4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_heart_1x4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_heart_1x4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_heart_2x4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_heart_2x4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_heart_3x4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_heart_3x4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_heart_4x4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_heart_4x4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hintglasses() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hintglasses", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hintglasses_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hintglasses_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hookshot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hookshot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hookshot_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hookshot_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hookshot_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hookshot_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_hookshot_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_hookshot_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_icerod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_icerod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_icerod_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_icerod_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_icerod_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_icerod_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_icerod_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_icerod_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_lamp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_lamp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_lamp_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_lamp_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_lamp_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_lamp_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_lostmaiamai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_lostmaiamai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_monsterguts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_monsterguts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_monsterhorn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_monsterhorn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_monstertail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_monstertail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_net() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_net", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_net_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_net_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_net_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_net_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_rupees() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_rupees", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_sandrod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_sandrod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_sandrod_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_sandrod_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_sandrod_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_sandrod_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_sandrod_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_sandrod_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_scootfruit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_scootfruit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_scootfruit_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_scootfruit_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_tornadorod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_tornadorod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_tornadorod_nice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_tornadorod_nice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_tornadorod_rented() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_tornadorod_rented", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_tornadorod_unavailable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_tornadorod_unavailable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_unusword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_unusword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minimize_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property title_ZALBWSE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title_ZALBWSE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
